spring.application.name=seeder
spring.main.web-application-type=none
spring.main.banner-mode=off

seed.db.identity-url=jdbc:postgresql://user-db:5432/user_service
seed.db.role-url=jdbc:postgresql://role-db:5432/role_service
seed.db.merchant-url=jdbc:postgresql://merchant-db:5432/merchant_service
seed.db.card-url=jdbc:postgresql://card-db:5432/card_service
seed.db.saldo-url=jdbc:postgresql://saldo-db:5432/saldo_service
seed.db.topup-url=jdbc:postgresql://topup-db:5432/topup_service
seed.db.transaction-url=jdbc:postgresql://transaction-db:5432/transaction_service
seed.db.transfer-url=jdbc:postgresql://transfer-db:5432/transfer_service
seed.db.withdraw-url=jdbc:postgresql://withdraw-db:5432/withdraw_service
seed.db.username=postgres
seed.db.password=password

seed.domains=

otel.service.name=seeder
otel.exporter.otlp.endpoint=http://otel-collector:4317
otel.traces.sampler=parentbased_always_on
