spring.application.name=withdraw-service
server.port=8096
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.datasource.url=jdbc:postgresql://withdraw-db:5432/withdraw_service
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration
spring.flyway.baseline-on-migrate=true
otel.service.name=withdraw-service
otel.exporter.otlp.endpoint=http://otel-collector:4317
otel.traces.sampler=parentbased_always_on
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Kafka Configuration
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
